"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { ArrowDownToLine, ArrowLeftRight, ArrowRight, ArrowUpRight, Bell, BookOpen, CalendarCheck2, CalendarDays, CalendarRange, ChartNoAxesCombined, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, ChevronsUpDown, CircleHelp, Clock3, Code2, GraduationCap, Grid2X2, House, Info, LayoutGrid, List, LogIn, Menu, MessagesSquare, Plus, Search, Settings2, ShieldCheck, Sparkles, Target, Users, X } from "lucide-react";
import { ACTIVE_STATUSES, BOOKING_LABELS, LAB_LABELS, LIMIT_MESSAGE, ROLE_LABELS, addDays, dayKey, formatDate, isActive, nextSaturday, slotsForDay, timeLabel, type Booking, type Lab, type Page, type Role, type WorkspaceData } from "@/lib/types";
import { Avatar, Brand, EmptyState, PrepIllustration, Spinner, StatusBadge, type ModalState, type Mutate, type MutationResult } from "@/components/ui";
import WorkspaceDialogs from "@/components/dialogs";

const PAGE_NAMES: Record<Page, string> = { schedule: "Расписание", progress: "Мой прогресс", materials: "Материалы курса", team: "Моя бригада", settings: "Настройки" };

export default function Workspace({ initialData }: { initialData: WorkspaceData }) {
  const [data, setData] = useState(initialData);
  const [page, setPage] = useState<Page>("schedule");
  const [courseId, setCourseId] = useState(initialData.courses[0]?.id ?? 1);
  const [selectedDay, setSelectedDay] = useState(initialData.defaultDate);
  const [weekStart, setWeekStart] = useState(initialData.defaultDate);
  const [view, setView] = useState<"grid" | "list">("grid");
  const [modal, setModal] = useState<ModalState | null>(null);
  const [menu, setMenu] = useState<"profile" | "course" | "notifications" | null>(null);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [toast, setToast] = useState<{ message: string; error?: boolean } | null>(null);
  const [readAt, setReadAt] = useState("");
  const [preselectedLab, setPreselectedLab] = useState<number | undefined>();
  const user = data.user;
  const student = user.role === "student";
  const course = data.courses.find(c => c.id === courseId) ?? data.courses[0];
  const courseLabs = useMemo(() => data.labs.filter(l => l.courseId === course?.id), [data.labs, course?.id]);
  const team = data.teams.find(t => t.id === user.teamId);
  const ownProgress = data.progress.filter(p => p.teamId === user.teamId && courseLabs.some(l => l.id === p.labId));
  const completed = ownProgress.filter(p => p.status === "completed").length;
  const activeBookings = data.bookings.filter(b => isActive(b) && (!student || b.teamId === user.teamId));
  const nextBooking = activeBookings.find(b => new Date(b.startAt).getTime() > Date.now());
  const unread = data.history.filter(h => !readAt || h.createdAt > readAt).length;
  const pageName = !student && page === "schedule" ? "Планирование" : !student && page === "progress" ? "Успеваемость" : !student && page === "team" ? "Бригады" : PAGE_NAMES[page];

  const closeModal = useCallback(() => { setModal(null); setError(""); }, []);
  const openModal = useCallback((value: ModalState) => { setError(""); setModal(value); setMenu(null); }, []);
  const navigate = useCallback((value: Page) => { setPage(value); setMobileOpen(false); setMenu(null); window.history.pushState(null, "", `#${value}`); window.scrollTo({ top: 0, behavior: "smooth" }); }, []);
  const refresh = useCallback(async () => { try { const response = await fetch("/api/workspace", { cache: "no-store" }); if (response.ok) setData(await response.json()); } catch { /* Keep the last synchronized view while offline. */ } }, []);

  useEffect(() => {
    const syncPage = () => { const hash = window.location.hash.slice(1) as Page; if (Object.keys(PAGE_NAMES).includes(hash)) setPage(hash); };
    syncPage(); window.addEventListener("popstate", syncPage); window.addEventListener("hashchange", syncPage);
    setReadAt(localStorage.getItem("pary-notifications-read") ?? "");
    if (!initialData.authenticated) fetch("/api/auth", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "demo", role: "student" }) }).then(r => r.json()).then(result => { if (result.data) setData(result.data); }).catch(() => setToast({ message: "Не удалось подключиться. Обновите страницу", error: true }));
    return () => { window.removeEventListener("popstate", syncPage); window.removeEventListener("hashchange", syncPage); };
  }, [initialData.authenticated]);
  useEffect(() => { const interval = setInterval(refresh, 30000); window.addEventListener("focus", refresh); return () => { clearInterval(interval); window.removeEventListener("focus", refresh); }; }, [refresh]);
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(null), 5000); return () => clearTimeout(timer); } }, [toast]);
  useEffect(() => { if (data.authenticated && data.user.role === "student" && data.teams.find(t => t.id === data.user.teamId)?.consentAt === null) setModal({ kind: "profile" }); }, [data]);

  const mutate: Mutate = useCallback(async (input, file) => {
    setBusy(true); setError("");
    try {
      let body: string | FormData; const headers: Record<string, string> = {};
      if (file) { const form = new FormData(); for (const [key, value] of Object.entries(input)) form.append(key, typeof value === "object" ? JSON.stringify(value) : String(value)); form.append("file", file); body = form; }
      else { body = JSON.stringify(input); headers["Content-Type"] = "application/json"; }
      const response = await fetch("/api/workspace", { method: "POST", headers, body }); const result = await response.json();
      if (!response.ok) throw new Error(result.error || "Не удалось сохранить изменения");
      setData(result.data); setToast({ message: result.message }); if (result.courseId) setCourseId(result.courseId);
      return result as MutationResult;
    } catch (e) { const message = e instanceof Error ? e.message : "Проверьте подключение к интернету"; setError(message); setToast({ message, error: true }); return null; }
    finally { setBusy(false); }
  }, []);

  const authenticate = useCallback(async (input: { role?: Role; username?: string; password?: string }) => {
    setBusy(true); setError("");
    try { const response = await fetch("/api/auth", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: input.role ? "demo" : "login", ...input }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result.data); setCourseId(result.data.courses[0]?.id ?? 1); setSelectedDay(result.data.defaultDate); setWeekStart(result.data.defaultDate); setMenu(null); setModal(null); setPage("schedule"); setToast({ message: result.message }); return true; }
    catch (e) { setError(e instanceof Error ? e.message : "Не удалось войти"); return false; }
    finally { setBusy(false); }
  }, []);
  const openLab = useCallback((labId: number, teamId?: number) => { openModal({ kind: "lab", labId, teamId }); if (user.role === "student" && data.progress.find(p => p.labId === labId && p.teamId === user.teamId)?.status === "new") void mutate({ action: "open_lab", labId }); }, [openModal, user, data.progress, mutate]);
  const bookLab = (labId: number) => { setPreselectedLab(labId); closeModal(); navigate("schedule"); setToast({ message: "Теперь выберите свободное время в расписании" }); };
  const changeDay = (day: string) => { setSelectedDay(day); if (day < weekStart || day > addDays(weekStart, 21)) setWeekStart(day); };
  const toggleNotifications = () => { const next = menu === "notifications" ? null : "notifications"; setMenu(next); if (next) { const now = new Date().toISOString(); setReadAt(now); localStorage.setItem("pary-notifications-read", now); } };
  const slotTimes = slotsForDay(selectedDay, course?.startTime, course?.endTime);
  const dayBookings = data.bookings.filter(b => dayKey(b.startAt) === selectedDay && (isActive(b) || b.status === "completed"));
  const freeSlots = slotTimes.filter(time => !dayBookings.some(b => b.startAt === time)).length;
  const upcomingLab = courseLabs.find(l => !ownProgress.some(p => p.labId === l.id && ["completed", "review"].includes(p.status)) && new Date(l.deadline).getTime() > Date.now());
  const deadlineDays = upcomingLab ? Math.max(0, Math.ceil((new Date(upcomingLab.deadline).getTime() - Date.now()) / 86400000)) : 0;

  const navItems = [
    { id: "progress" as Page, icon: ChartNoAxesCombined, label: student ? "Мой прогресс" : "Успеваемость" },
    { id: "schedule" as Page, icon: CalendarDays, label: student ? "Расписание и запись" : "Планирование" },
    { id: "materials" as Page, icon: BookOpen, label: user.role === "admin" ? "Курсы и материалы" : "Материалы курса" },
    { id: "team" as Page, icon: Users, label: student ? "Моя бригада" : "Бригады" },
    ...(user.role === "admin" ? [{ id: "settings" as Page, icon: Settings2, label: "Настройки" }] : []),
  ];

  return <div className="app-shell">
    {menu && <button className="menu-scrim" aria-label="Закрыть меню" onClick={() => setMenu(null)} />}
    {mobileOpen && <button className="mobile-scrim" aria-label="Закрыть навигацию" onClick={() => setMobileOpen(false)} />}
    <aside className={`sidebar ${mobileOpen ? "sidebar-open" : ""}`}>
      <button className="brand-button" onClick={() => navigate("schedule")} aria-label="Пары — на главную"><Brand /><span className="beta-tag">beta</span></button>
      <div className="course-switch-wrap"><button className="course-switch" onClick={() => setMenu(menu === "course" ? null : "course")} aria-expanded={menu === "course"}><span className="course-icon"><GraduationCap size={20} /></span><span className="course-switch-text"><small>ВАШ КУРС</small><strong>{course?.title}</strong></span><ChevronsUpDown size={14} /></button>{menu === "course" && <div className="popover course-popover"><div className="popover-label">Мои курсы</div>{data.courses.map(c => <button key={c.id} className="course-option" onClick={() => { setCourseId(c.id); setMenu(null); }}><BookOpen size={17} /><span>{c.title}<small>{c.groupCode} · {c.semester}</small></span>{c.id === courseId && <Check size={16} />}</button>)}{user.role === "admin" && <button className="popover-action" onClick={() => openModal({ kind: "create-course" })}><Plus size={16} /> Создать курс</button>}</div>}</div>
      <div className="nav-label">РАБОЧЕЕ ПРОСТРАНСТВО</div>
      <nav className="main-nav" aria-label="Основная навигация">{navItems.map(item => <button key={item.id} className={`nav-item ${page === item.id ? "active" : ""}`} onClick={() => navigate(item.id)} aria-current={page === item.id ? "page" : undefined}><item.icon size={19} strokeWidth={1.8} /><span>{item.label}</span>{item.id === "schedule" && <span className="nav-count">{student ? activeBookings.length : activeBookings.filter(b => b.status === "pending").length}</span>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="sidebar-tip"><div className="tip-symbol"><Sparkles size={19} /><span className="tiny-sparkle">✧</span></div><h3>К защите готовы?</h3><p>Теория, задания и вопросы —<br />всё, что нужно для следующего шага.</p><button onClick={() => navigate("materials")}>Перейти к материалам <ArrowUpRight size={15} /></button></div><button className="help-nav" onClick={() => openModal({ kind: "help" })}><CircleHelp size={18} />Помощь и правила<ArrowUpRight size={14} /></button><div className="sidebar-profile"><button onClick={() => setMenu(menu === "profile" ? null : "profile")} aria-expanded={menu === "profile"}><Avatar name={student ? "Бригада 12".replace("12", String(team?.number ?? 12)) : user.name} /><span><strong>{user.name}</strong><small>{ROLE_LABELS[user.role]}{student ? ` · ${team?.size ?? 3} участника` : " · Демо-кабинет"}</small></span><ChevronsUpDown size={15} /></button></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumbs"><button className="icon-button mobile-menu-button" aria-label="Открыть навигацию" onClick={() => setMobileOpen(true)}><Menu size={22} /></button><House size={15} /><span>Рабочее пространство</span><ChevronRight size={12} /><strong>{pageName}</strong></div><div className="topbar-actions"><span className="semester-label"><span />{course?.semester}</span><div className="notification-wrap"><button className={`icon-button notification-button ${menu === "notifications" ? "selected" : ""}`} onClick={toggleNotifications} aria-label="Уведомления" aria-expanded={menu === "notifications"}><Bell size={19} />{unread > 0 && <span className="notification-dot" />}</button>{menu === "notifications" && <div className="popover notification-popover"><div className="popover-title"><h3>Уведомления</h3><span className="mini-badge">{data.history.length}</span></div>{data.history.length ? data.history.slice(0, 6).map(item => <button className="notification-item" key={item.id} onClick={() => item.labId ? openLab(item.labId, item.teamId) : openModal({ kind: student ? "profile" : "team", teamId: item.teamId } as ModalState)}><span className="notification-item-icon">{item.action === "file" ? <BookOpen size={16} /> : <CheckCircle2 size={16} />}</span><span><strong>{item.detail}</strong><small>{item.actor} · {formatDate(item.createdAt, { day: "numeric", month: "short" })}</small></span></button>) : <div className="popover-empty">Новых событий пока нет</div>}<div className="notification-footer"><CheckCheckIcon />Все события сохраняются в истории работ</div></div>}</div><span className="topbar-divider" /><button className="topbar-profile" onClick={() => setMenu(menu === "profile" ? null : "profile")} aria-label="Открыть меню профиля"><Avatar name={student ? team?.members[0]?.name || user.name : user.name} /><ChevronDown size={13} /></button></div></header>
      {menu === "profile" && <div className="popover profile-popover"><div className="profile-popover-head"><Avatar name={user.name} /><div><strong>{user.name}</strong><small>{ROLE_LABELS[user.role]}</small></div></div><div className="popover-label">ПОСМОТРЕТЬ ДЕМО-КАБИНЕТ</div>{(["student", "teacher", "admin"] as Role[]).map(role => <button className={`role-option ${user.role === role ? "current" : ""}`} key={role} disabled={busy} onClick={() => void authenticate({ role })}>{role === "student" ? <GraduationCap size={18} /> : role === "teacher" ? <BookOpen size={18} /> : <Settings2 size={18} />}<span>{ROLE_LABELS[role]}</span>{user.role === role && <Check size={15} />}</button>)}<div className="popover-separator" />{student && <button className="role-option" onClick={() => openModal({ kind: "profile" })}><Users size={17} />Данные бригады</button>}<button className="role-option" onClick={() => openModal({ kind: "login" })}><LogIn size={17} />Войти по логину</button><p className="demo-disclaimer">Демо-кабинеты доступны для знакомства с возможностями системы.</p></div>}
      <main className="main-content"><div className="page-heading"><div><div className="page-eyebrow">{course?.groupCode}<span>·</span>{student ? `Бригада №${team?.number ?? "—"}` : ROLE_LABELS[user.role]}</div><h1>{page === "schedule" ? student ? "Расписание и запись" : "Планирование занятий" : page === "progress" ? student ? "Каждый шаг — ближе к цели" : "Прогресс бригад" : page === "materials" ? "Всё для вашей следующей работы" : page === "team" ? student ? "Учиться лучше вместе" : "Бригады курса" : "Настройки расписания"}</h1><p>{page === "schedule" ? student ? "Выберите удобное время для консультации или сдачи работы." : "Управляйте заявками, принимайте работы и следите за расписанием." : page === "progress" ? "Все лабораторные, результаты и история — в одном месте." : page === "materials" ? "Изучайте теорию, выполняйте задания и готовьтесь к защите." : page === "team" ? "Ваше маленькое сообщество для больших результатов." : "Настройте рабочие часы и правила записи на вашем курсе."}</p></div><button className="button button-white heading-help" onClick={() => openModal({ kind: "help" })}><CircleHelp size={16} />Как это работает</button></div>
        {page === "schedule" && <>
          <div className="stats-grid"><div className="stat-card"><div className="stat-heading">{student ? "Активные брони" : "Заявки на проверку"}<span className="stat-icon purple"><CalendarCheck2 size={19} /></span></div><div className="stat-value">{student ? activeBookings.length : activeBookings.filter(b => b.status === "pending").length}<span>{student ? "/ 2" : "заявки"}</span>{student && <span className="booking-meter"><i className={activeBookings.length >= 1 ? "filled" : ""} /><i className={activeBookings.length >= 2 ? "filled" : ""} /></span>}</div><p>{student ? activeBookings.length >= 2 ? "Лимит достигнут — дождитесь завершения" : <>Можно забронировать ещё <strong>{2 - activeBookings.length} {activeBookings.length === 1 ? "слот" : "слота"}</strong></> : "Ждут вашего подтверждения"}</p></div><div className="stat-card"><div className="stat-heading">{student ? "Ближайшая встреча" : "Ближайшая суббота"}<span className="stat-icon peach"><Clock3 size={19} /></span></div><div className="stat-value stat-date">{nextBooking ? formatDate(nextBooking.startAt, { day: "numeric", month: "long" }) : formatDate(`${selectedDay}T12:00:00Z`)}{nextBooking && <span className="time-tag">{timeLabel(nextBooking.startAt)}</span>}</div><p>{nextBooking ? <><span className="mini-status-dot" />{BOOKING_LABELS[nextBooking.status]} · 15 минут</> : "Самое время выбрать удобный слот"}</p></div><div className="stat-card"><div className="stat-heading">{student ? "Прогресс по курсу" : "Активные бригады"}<span className="stat-icon mint">{student ? <ChartNoAxesCombined size={19} /> : <Users size={19} />}</span></div><div className="stat-value">{student ? completed : data.teams.length}<span>{student ? `из ${courseLabs.length} работ` : "на курсе"}</span></div><div className="stat-progress"><span style={{ width: `${student ? (completed / (courseLabs.length || 1)) * 100 : 75}%` }} /></div></div></div>
          <div className="schedule-layout"><div className="schedule-main"><section className="calendar-card"><div className="calendar-card-heading"><h2>Выберите время<span className="calendar-heading-dot" /></h2><div className="view-switch" aria-label="Вид расписания"><button className={view === "grid" ? "selected" : ""} onClick={() => setView("grid")} aria-pressed={view === "grid"}><LayoutGrid size={14} />Сетка</button><button className={view === "list" ? "selected" : ""} onClick={() => setView("list")} aria-pressed={view === "list"}><List size={15} />Список</button></div></div><div className="calendar-navigation"><div className="calendar-date-title"><CalendarDays size={17} /><h3>Суббота, {formatDate(`${selectedDay}T12:00:00Z`)}</h3></div><div className="calendar-navigation-buttons"><button className="today-button" onClick={() => { const day = nextSaturday(); setSelectedDay(day); setWeekStart(day); }}>Ближайшая</button><button className="icon-button arrow-button" aria-label="Предыдущая суббота" onClick={() => changeDay(addDays(selectedDay, -7))}><ChevronLeft size={16} /></button><button className="icon-button arrow-button" aria-label="Следующая суббота" onClick={() => changeDay(addDays(selectedDay, 7))}><ChevronRight size={16} /></button></div></div><div className="date-tabs">{[0, 7, 14, 21].map(offset => { const day = addDays(weekStart, offset); return <button key={day} className={`date-tab ${selectedDay === day ? "selected" : ""}`} onClick={() => setSelectedDay(day)} aria-pressed={selectedDay === day}><span>СУББОТА</span><strong>{formatDate(`${day}T12:00:00Z`)}</strong>{day === data.defaultDate && <span className="date-tab-dot" />}</button>; })}</div><div className="calendar-legend"><div className="legend-items"><span><i className="legend-free" />Свободно</span><span><i className="legend-occupied" />Занято</span><span><i className="legend-own" />{student ? "Ваша бронь" : "Ожидает решения"}</span></div><span className="slot-duration"><Clock3 size={12} />15 мин</span></div>{preselectedLab && <div className="selected-lab-notice"><BookOpen size={14} />Запись на ЛР №{data.labs.find(l => l.id === preselectedLab)?.number}<button onClick={() => setPreselectedLab(undefined)} aria-label="Убрать выбранную работу"><X size={13} /></button></div>}<div className={`slots ${view === "list" ? "slots-list" : ""}`}>{slotTimes.map(time => {
            const booking = dayBookings.find(b => b.startAt === time); const own = booking?.teamId === user.teamId; const late = new Date(time).getTime() - Date.now() < 86400000; const limit = student && activeBookings.length >= 2; const bookedTeam = data.teams.find(t => t.id === booking?.teamId);
            const disabled = booking ? student && !own : !student || limit || late;
            return <button key={time} className={`time-slot ${booking ? own ? "own-slot" : !student && booking.status === "pending" ? "pending-slot" : "occupied-slot" : late ? "past-slot" : "free-slot"} ${modal?.kind === "booking" && modal.startAt === time ? "selected-slot" : ""}`} disabled={disabled} aria-label={`${timeLabel(time)} — ${booking ? own ? "Ваша бронь" : "Занято" : late ? "Запись закрыта" : "Свободно"}`} title={booking ? own ? "Посмотреть вашу запись" : !student ? "Открыть заявку" : "Этот слот занят другой бригадой" : limit ? LIMIT_MESSAGE : late ? "Запись закрывается за 24 часа" : !student ? "Свободное время для записи студентов" : "Записаться на это время"} onClick={() => booking ? openModal({ kind: "review", bookingId: booking.id }) : openModal({ kind: "booking", startAt: time, labId: preselectedLab })}><strong>{timeLabel(time)}{own && <Check size={11} />}</strong><span>{booking ? own ? "Ваша бронь" : !student ? `Бригада №${bookedTeam?.number ?? "—"}` : "Занято" : late ? "Запись закрыта" : "Свободно"}</span>{view === "list" && <ChevronRight size={15} />}</button>;
          })}</div><div className="calendar-footer"><span><Info size={13} />Время московское, UTC+3</span><span className="free-count"><span />Свободно {freeSlots} из {slotTimes.length}</span></div></section><div className={`schedule-note ${student && activeBookings.length >= 2 ? "limit-note" : ""}`}><span className="note-icon"><Info size={18} /></span><p><strong>{student && activeBookings.length >= 2 ? "Все ваши слоты уже забронированы" : "Планы могут меняться — это нормально"}</strong><span>{student && activeBookings.length >= 2 ? LIMIT_MESSAGE : "Отменить или перенести бронь можно не позднее чем за 24 часа до встречи."}</span></p></div></div>
          <aside className="schedule-aside"><div className="section-heading"><h2>{student ? "Мои брони" : "Ожидают решения"}<span className="mini-badge">{student ? activeBookings.length : activeBookings.filter(b => b.status === "pending").length}</span></h2><button className="text-button" onClick={() => openModal({ kind: "all-bookings" })}>Все<ChevronRight size={13} /></button></div><div className="booking-cards">{(student ? activeBookings : activeBookings.filter(b => b.status === "pending")).slice(0, student ? 2 : 2).map(booking => <BookingCard key={booking.id} booking={booking} data={data} onOpen={openModal} onLab={openLab} />)}{(student ? activeBookings : activeBookings.filter(b => b.status === "pending")).length === 0 && <div className="no-bookings"><CalendarCheck2 size={28} /><h3>{student ? "Впереди — новые встречи" : "Все заявки рассмотрены"}</h3><p>{student ? "Выберите свободное время слева, а мы сохраним его для вас." : "Новые записи студентов появятся здесь."}</p></div>}</div>{student && upcomingLab && <button className="deadline-card" onClick={() => openLab(upcomingLab.id)}><div className="deadline-eyebrow"><span><Clock3 size={14} /></span>БЛИЖАЙШИЙ ДЕДЛАЙН<ArrowUpRight size={14} /></div><h3>ЛР №{upcomingLab.number} · {upcomingLab.title}</h3><div><span>{formatDate(upcomingLab.deadline)}</span><strong>Через {deadlineDays} дн.</strong></div></button>}<div className="preparation-card"><PrepIllustration /><span className="small-kicker">ШАГ ЗА ШАГОМ</span><h3>Немного подготовки.<br />Больше уверенности.</h3><p>Загляните в вопросы к защите<br />перед встречей с преподавателем.</p><button onClick={() => navigate("materials")}>Открыть материалы<ArrowUpRight size={15} /></button></div></aside></div>
        </>}
        {page === "progress" && <ProgressPage data={data} labs={courseLabs} onLab={openLab} onTeam={id => openModal({ kind: "team", teamId: id })} />}
        {page === "materials" && <MaterialsPage data={data} labs={courseLabs} onLab={openLab} onModal={openModal} />}
        {page === "team" && <TeamPage data={data} labs={courseLabs} onModal={openModal} />}
        {page === "settings" && <SettingsPage data={data} courseId={courseId} busy={busy} mutate={mutate} />}
        <footer className="page-footer"><span><ShieldCheck size={13} />Файлы и история изменений надёжно сохраняются</span><span>Пары — учиться проще вместе</span></footer>
      </main>
    </div>
    {modal && <WorkspaceDialogs modal={modal} data={data} courseId={courseId} busy={busy} error={error} onClose={closeModal} onChange={openModal} mutate={mutate} authenticate={authenticate} onBookLab={bookLab} />}
    {toast && <div className={`toast ${toast.error ? "toast-error" : ""}`} role="status">{toast.error ? <Info size={19} /> : <CheckCircle2 size={19} />}<span>{toast.message}</span><button onClick={() => setToast(null)} aria-label="Закрыть уведомление"><X size={16} /></button></div>}
  </div>;
}

function CheckCheckIcon() { return <Check size={13} />; }
function BookingCard({ booking, data, onOpen, onLab }: { booking: Booking; data: WorkspaceData; onOpen: (modal: ModalState) => void; onLab: (id: number) => void }) {
  const lab = data.labs.find(l => l.id === booking.labId); const course = data.courses.find(c => c.id === lab?.courseId); const student = data.user.role === "student"; const canChange = new Date(booking.startAt).getTime() - Date.now() >= 86400000; const team = data.teams.find(t => t.id === booking.teamId);
  return <article className="booking-card"><div className="booking-card-top"><StatusBadge status={booking.status} kind="booking" /><button className="icon-button small-icon-button" aria-label="Подробности брони" onClick={() => onOpen({ kind: "review", bookingId: booking.id })}><ArrowUpRight size={16} /></button></div><button className="booking-lab-title" onClick={() => onLab(booking.labId)}><span>ЛАБОРАТОРНАЯ РАБОТА №{lab?.number}</span><h3>{lab?.title}</h3></button><div className="booking-meta"><span><CalendarDays size={15} />{formatDate(booking.startAt)}, суббота</span><span><Clock3 size={15} />{timeLabel(booking.startAt)} — {timeLabel(new Date(new Date(booking.startAt).getTime() + 900000))}<span className="duration-label">15 мин</span></span></div><div className="purpose-tag">{booking.purpose === "defense" ? <GraduationCap size={13} /> : <MessagesSquare size={13} />}{booking.purpose === "defense" ? "Сдача лабораторной" : "Консультация"}</div><div className="booking-person"><Avatar name={student ? course?.teacher ?? "Елена Смирнова" : `Бригада ${team?.number}`} color={student ? 2 : 0} /><span><strong>{student ? course?.teacher : `Бригада №${team?.number}`}</strong><small>{student ? "Преподаватель" : `${team?.size} участника`}</small></span></div>{student ? <><button className="button button-white reschedule-button" disabled={!canChange} title={!canChange ? "До встречи осталось менее 24 часов" : undefined} onClick={() => onOpen({ kind: "reschedule", bookingId: booking.id })}><ArrowLeftRight size={14} />Перезаписаться</button><button className="cancel-booking-button" disabled={!canChange} onClick={() => onOpen({ kind: "cancel", bookingId: booking.id })}>Отменить бронь</button></> : <button className="button button-primary full-width" onClick={() => onOpen({ kind: "review", bookingId: booking.id })}>Рассмотреть заявку<ArrowRight size={14} /></button>}</article>;
}

function ProgressPage({ data, labs, onLab, onTeam }: { data: WorkspaceData; labs: Lab[]; onLab: (id: number, teamId?: number) => void; onTeam: (id: number) => void }) {
  const [filter, setFilter] = useState("all"); const [search, setSearch] = useState(""); const student = data.user.role === "student";
  const progress = data.progress.filter(p => p.teamId === data.user.teamId && labs.some(l => l.id === p.labId)); const completed = progress.filter(p => p.status === "completed"); const score = completed.reduce((sum, p) => sum + Number(p.score ?? 0), 0);
  if (!student) return <section className="panel"><div className="panel-heading"><h2>Все бригады<span className="mini-badge">{data.teams.length}</span></h2><div className="search-field"><Search size={16} /><input placeholder="Найти бригаду..." value={search} onChange={e => setSearch(e.target.value)} /></div></div><div className="responsive-table"><table><thead><tr><th>Бригада</th><th>Участники</th><th>Прогресс</th><th>Баллы</th><th /></tr></thead><tbody>{data.teams.filter(t => `${t.number} ${t.members.map(m => m.name).join(" ")}`.toLowerCase().includes(search.toLowerCase())).map(t => { const p = data.progress.filter(x => x.teamId === t.id && labs.some(l => l.id === x.labId)); const done = p.filter(x => x.status === "completed"); return <tr key={t.id} onClick={() => onTeam(t.id)}><td><strong>Бригада №{t.number}</strong></td><td><div className="avatar-stack">{t.members.map((m, i) => <Avatar key={i} name={m.name || `Участник ${i + 1}`} color={i} />)}<span>{t.size} участника</span></div></td><td><div className="table-progress"><span><i style={{ width: `${done.length / (labs.length || 1) * 100}%` }} /></span>{done.length} / {labs.length}</div></td><td><strong>{done.reduce((sum, x) => sum + Number(x.score || 0), 0)}</strong></td><td><button className="icon-button" aria-label={`Открыть бригаду ${t.number}`}><ChevronRight size={17} /></button></td></tr>; })}</tbody></table></div></section>;
  const filtered = labs.filter(l => l.title.toLowerCase().includes(search.toLowerCase()) && (filter === "all" || (progress.find(p => p.labId === l.id)?.status ?? "new") === filter));
  return <><div className="progress-overview"><div className="progress-circle" style={{ background: `conic-gradient(var(--purple) ${completed.length / (labs.length || 1) * 360}deg, #eeeaf6 0deg)` }}><span>{Math.round(completed.length / (labs.length || 1) * 100)}<small>%</small></span></div><div><span className="small-kicker">ВАШ ПУТЬ НА КУРСЕ</span><h2>{completed.length} из {labs.length} работ уже позади</h2><p>Хороший темп! Следующая маленькая победа — совсем рядом.</p></div><div className="overview-score"><span>Всего баллов</span><strong>{new Intl.NumberFormat("ru-RU").format(score)}</strong><small>Вы отлично справляетесь</small></div></div><section className="panel progress-panel"><div className="panel-toolbar"><div className="filter-tabs">{[{ id: "all", label: "Все работы" }, { id: "in_progress", label: "В работе" }, { id: "review", label: "На проверке" }, { id: "completed", label: "Выполнены" }].map(item => <button key={item.id} className={filter === item.id ? "selected" : ""} onClick={() => setFilter(item.id)}>{item.label}{item.id === "all" && <span>{labs.length}</span>}</button>)}</div><div className="search-field"><Search size={15} /><input placeholder="Найти работу..." value={search} onChange={e => setSearch(e.target.value)} /></div></div><div className="lab-rows">{filtered.length ? filtered.map(lab => { const p = progress.find(item => item.labId === lab.id); return <div className="lab-row" key={lab.id}><button className="lab-row-main" onClick={() => onLab(lab.id)}><span className={`lab-number lab-number-${p?.status ?? "new"}`}>{p?.status === "completed" ? <Check size={22} /> : String(lab.number).padStart(2, "0")}</span><span className="lab-row-title"><small>ЛАБОРАТОРНАЯ РАБОТА №{lab.number}</small><h3>{lab.title}</h3><span><CalendarDays size={12} />До {formatDate(lab.deadline)}</span></span><StatusBadge status={p?.status ?? "new"} /><span className="lab-row-score">{p?.score !== null && p?.score !== undefined ? <><strong>{p.score}</strong><small>баллов</small></> : <span>—</span>}</span><ChevronRight size={18} /></button><details className="lab-history-preview"><summary><Clock3 size={12} />История работы<span>{data.history.filter(h => h.labId === lab.id).length}</span><ChevronDown size={12} /></summary><div>{data.history.filter(h => h.labId === lab.id).length ? data.history.filter(h => h.labId === lab.id).slice(0, 5).map(h => <p key={h.id}><span>{formatDate(h.createdAt, { day: "numeric", month: "short" })}</span>{h.detail}<small>{h.actor}</small></p>) : <p>Откройте материалы, чтобы начать работу. Все изменения появятся здесь.</p>}</div></details></div>; }) : <EmptyState title="Таких работ пока нет" description="Попробуйте другой статус или измените поисковый запрос." />}</div></section></>;
}

function MaterialsPage({ data, labs, onLab, onModal }: { data: WorkspaceData; labs: Lab[]; onLab: (id: number) => void; onModal: (modal: ModalState) => void }) {
  const [search, setSearch] = useState(""); const filtered = labs.filter(l => `${l.title} ${l.number}`.toLowerCase().includes(search.toLowerCase()));
  return <><div className="materials-toolbar"><div className="search-field"><Search size={17} /><input placeholder="Поиск по названию лабораторной..." value={search} onChange={e => setSearch(e.target.value)} /></div><div className="toolbar-actions">{data.user.role === "admin" ? <><button className="button button-white" onClick={() => onModal({ kind: "create-course" })}><Plus size={16} />Новый курс</button><button className="button button-primary" onClick={() => onModal({ kind: "create-lab" })}><Plus size={16} />Добавить работу</button></> : <span className="muted-label">{labs.length} лабораторных работ</span>}</div></div><div className="materials-grid">{filtered.map(lab => { const status = data.progress.find(p => p.labId === lab.id && p.teamId === data.user.teamId)?.status ?? "new"; return <article className="material-card" key={lab.id}><div className="material-card-top"><span className={`material-icon material-icon-${lab.number % 4}`}><Code2 size={24} /></span><span className="material-number">ЛР {String(lab.number).padStart(2, "0")}</span></div><button className="material-title" onClick={() => onLab(lab.id)}><h2>{lab.title}</h2></button><p>{lab.theory.slice(0, 115)}…</p><div className="material-card-meta"><span><CalendarDays size={13} />До {formatDate(lab.deadline)}</span>{data.user.role === "student" && <StatusBadge status={status} />}</div><button className="material-open" onClick={() => onLab(lab.id)}>Открыть материалы<ArrowUpRight size={16} /></button></article>; })}</div>{!filtered.length && <EmptyState title={search ? "Ничего не нашлось" : "Начало нового курса"} description={search ? "Попробуйте поискать по другому названию." : "Лабораторные появятся здесь, как только администратор добавит материалы."} />}</>;
}

function TeamPage({ data, labs, onModal }: { data: WorkspaceData; labs: Lab[]; onModal: (modal: ModalState) => void }) {
  const [search, setSearch] = useState(""); const student = data.user.role === "student"; const team = data.teams.find(t => t.id === data.user.teamId);
  if (!student) return <section className="panel"><div className="panel-heading"><h2>Участники курса<span className="mini-badge">{data.teams.length} бригад</span></h2><div className="toolbar-actions"><div className="search-field"><Search size={16} /><input placeholder="Номер или имя..." value={search} onChange={e => setSearch(e.target.value)} /></div>{data.user.role === "admin" && <button className="button button-primary" onClick={() => onModal({ kind: "create-team" })}><Plus size={15} />Создать бригаду</button>}</div></div><div className="team-list">{data.teams.filter(t => `${t.number} ${t.members.map(m => m.name).join(" ")}`.toLowerCase().includes(search.toLowerCase())).map(t => <button className="team-list-row" key={t.id} onClick={() => onModal({ kind: "team", teamId: t.id })}><span className="team-list-avatar"><Users size={23} /></span><span><strong>Бригада №{t.number}</strong><small>{t.members.map(m => m.name || "Данные ещё не заполнены").join(", ")}</small></span><span className="team-size-label">{t.size} участника</span><span className={`consent-tag ${t.consentAt ? "given" : ""}`}>{t.consentAt ? <><ShieldCheck size={12} />ПДн подтверждено</> : "Ожидает регистрации"}</span><ChevronRight size={18} /></button>)}</div></section>;
  if (!team) return <EmptyState title="Бригада не найдена" description="Обратитесь к администратору курса." />;
  return <><div className="team-banner"><div className="team-banner-icon"><Users size={31} /></div><div><span className="small-kicker">ВАША КОМАНДА</span><h2>Бригада №{team.number}</h2><p>{team.size} участника · {data.courses[0]?.groupCode} · Один общий результат</p></div><button className="button button-white" onClick={() => onModal({ kind: "profile" })}><Settings2 size={15} />Редактировать данные</button></div><div className="members-grid">{team.members.map((member, i) => <article className="member-card" key={i}><div className="member-card-top"><Avatar name={member.name || `Участник ${i + 1}`} color={i} /><span>УЧАСТНИК {i + 1}</span></div><h3>{member.name || "Заполните имя"}</h3><p>{member.contact || "Контакт не указан"}</p><span className="member-status"><span />В вашей бригаде</span></article>)}</div><div className="team-info-grid"><section className="panel team-info-panel"><span className="team-info-icon"><ShieldCheck size={23} /></span><h3>Ваши данные под защитой</h3><p>Имена и контакты видны только вашей бригаде, преподавателю и администратору. Они используются для организации учебного процесса.</p><span className="consent-date">{team.consentAt ? <><CheckCircle2 size={14} />Согласие получено {formatDate(team.consentAt)}</> : "Необходимо согласие участников"}</span></section><section className="panel team-info-panel"><span className="team-info-icon purple-text"><Target size={23} /></span><h3>Одна бригада — общий прогресс</h3><p>Все участники используют один аккаунт. Брони, версии отчётов и баллы общие для всей команды.</p><div className="team-summary-numbers"><strong>{labs.length}<span>лабораторных</span></strong><strong>2<span>активные брони</span></strong><strong>15<span>минут на встречу</span></strong></div></section></div></>;
}

function SettingsPage({ data, courseId, busy, mutate }: { data: WorkspaceData; courseId: number; busy: boolean; mutate: Mutate }) {
  const course = data.courses.find(c => c.id === courseId); if (data.user.role !== "admin" || !course) return <EmptyState title="Этот раздел для администратора" description="Настройки курса доступны только администратору." />;
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); await mutate({ action: "update_schedule", courseId, startTime: form.get("startTime"), endTime: form.get("endTime") }); };
  return <div className="settings-layout"><form className="panel settings-panel" key={courseId} onSubmit={submit}><div className="panel-heading"><h2><CalendarRange size={19} />Рабочее расписание</h2></div><div className="settings-body"><label className="field-label">День занятий</label><div className="weekday-picker">{["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"].map(day => <span key={day} className={day === "Сб" ? "selected" : ""}>{day}</span>)}</div><div className="form-two-columns"><label className="field">Начало<input name="startTime" type="time" step="900" defaultValue={course.startTime} required /></label><label className="field">Окончание<input name="endTime" type="time" step="900" defaultValue={course.endTime} required /></label></div><label className="field">Длительность встречи<div className="readonly-field"><Clock3 size={16} />15 минут<span>Фиксировано</span></div></label><div className="info-box"><Info size={17} /><p>Изменения применяются ко всем субботам. Активные брони не должны выходить за новые рабочие часы.</p></div><button className="button button-primary" disabled={busy}>{busy ? <Spinner /> : <Check size={16} />}Сохранить расписание</button></div></form><section className="panel rules-panel"><h2>Правила курса</h2>{[{ value: "2 брони", text: "Максимум активных записей на бригаду" }, { value: "24 часа", text: "Минимальный срок записи, отмены и переноса" }, { value: "10 МБ", text: "Максимальный размер PDF-отчёта" }, { value: "Без ограничений", text: "Числовая шкала оценки, включая дробные баллы" }].map(rule => <div className="rule-setting" key={rule.value}><strong>{rule.value}</strong><p>{rule.text}</p></div>)}<small>Эти правила проверяются на сервере и действуют для всех бригад.</small></section></div>;
}
